kind: ConfigMap
metadata:
  name: {{ include "user-workload.name" . }}-db-cleanup
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: PreDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,BeforeHookCreation
apiVersion: v1
data:
  playbook.yaml: |
    ---
    - name: Database cleanup for {{ .Values.tenant.username }}
      hosts: localhost
      gather_facts: false
      vars:
        tenant_username: {{ .Values.tenant.username }}
        db_host: "postgres.{{ .Values.sharedDatabase.namespace }}.svc.cluster.local"
        db_name: {{ .Values.sharedDatabase.database | quote }}
        db_admin: {{ .Values.sharedDatabase.adminUser | quote }}
        db_admin_pass: {{ .Values.sharedDatabase.adminPassword | quote }}
      tasks:
        - name: Drop schema
          community.postgresql.postgresql_query:
            login_host: "{{ '{{' }} db_host {{ '}}' }}"
            login_user: "{{ '{{' }} db_admin {{ '}}' }}"
            login_password: "{{ '{{' }} db_admin_pass {{ '}}' }}"
            db: "{{ '{{' }} db_name {{ '}}' }}"
            query: DROP SCHEMA IF EXISTS {{ '{{' }} tenant_username {{ '}}' }} CASCADE
          ignore_errors: true

        - name: Revoke role from admin
          community.postgresql.postgresql_query:
            login_host: "{{ '{{' }} db_host {{ '}}' }}"
            login_user: "{{ '{{' }} db_admin {{ '}}' }}"
            login_password: "{{ '{{' }} db_admin_pass {{ '}}' }}"
            db: "{{ '{{' }} db_name {{ '}}' }}"
            query: REVOKE {{ '{{' }} tenant_username {{ '}}' }} FROM {{ '{{' }} db_admin {{ '}}' }}
          ignore_errors: true

        - name: Drop role
          community.postgresql.postgresql_user:
            name: "{{ '{{' }} tenant_username {{ '}}' }}"
            login_host: "{{ '{{' }} db_host {{ '}}' }}"
            login_user: "{{ '{{' }} db_admin {{ '}}' }}"
            login_password: "{{ '{{' }} db_admin_pass {{ '}}' }}"
            state: absent
          ignore_errors: true
