kind: ConfigMap
metadata:
  name: {{ include "user-workload.name" . }}-helpdesk-cleanup
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: PreDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,BeforeHookCreation
apiVersion: v1
data:
  playbook.yaml: |
    ---
    - name: Helpdesk cleanup for {{ .Values.tenant.username }}
      hosts: localhost
      gather_facts: false
      vars:
        tenant_username: {{ .Values.tenant.username }}
        hd_url: "http://helpdesk.{{ .Values.helpdesk.namespace }}.svc.cluster.local:8118"
        admin_user: {{ .Values.helpdesk.admin.username | quote }}
        admin_pass: {{ .Values.helpdesk.admin.password | quote }}
        group_name: "Group {{ .Values.tenant.username }}"
      tasks:
        - name: Admin login
          ansible.builtin.uri:
            url: "{{ '{{' }} hd_url {{ '}}' }}/api/v1/login"
            method: POST
            body_format: json
            body:
              username: "{{ '{{' }} admin_user {{ '}}' }}"
              password: "{{ '{{' }} admin_pass {{ '}}' }}"
            validate_certs: false
          register: r_admin_login
          ignore_errors: true

        - name: Delete user
          ansible.builtin.uri:
            url: "{{ '{{' }} hd_url {{ '}}' }}/api/v1/users/{{ '{{' }} tenant_username {{ '}}' }}"
            method: DELETE
            headers:
              accesstoken: "{{ '{{' }} r_admin_login.json.accessToken {{ '}}' }}"
            status_code: [200, 404]
            validate_certs: false
          when: r_admin_login is success
          ignore_errors: true

        - name: Get groups
          ansible.builtin.uri:
            url: "{{ '{{' }} hd_url {{ '}}' }}/api/v1/groups"
            method: GET
            headers:
              accesstoken: "{{ '{{' }} r_admin_login.json.accessToken {{ '}}' }}"
            validate_certs: false
          register: r_groups
          when: r_admin_login is success
          ignore_errors: true

        - name: Delete group
          ansible.builtin.uri:
            url: "{{ '{{' }} hd_url {{ '}}' }}/api/v1/groups/{{ '{{' }} item._id {{ '}}' }}"
            method: DELETE
            headers:
              accesstoken: "{{ '{{' }} r_admin_login.json.accessToken {{ '}}' }}"
            status_code: [200, 404]
            validate_certs: false
          loop: "{{ '{{' }} r_groups.json.groups | selectattr('name', 'equalto', group_name) | list {{ '}}' }}"
          when:
            - r_admin_login is success
            - r_groups is success
          ignore_errors: true
