apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: camel-credentials
  namespace: {{ include "user-workload.namespace" . }}
  labels:
    {{- include "user-workload.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  data:
    - secretKey: MATRIX_TOKEN
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/matrix
        property: token
    - secretKey: MATRIX_ROOM
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/matrix
        property: room
    - secretKey: ROCKETCHAT_TOKEN
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/rocketchat
        property: token
    - secretKey: ROCKETCHAT_USERID
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/rocketchat
        property: userId
    - secretKey: ROCKETCHAT_CHANNEL
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/rocketchat
        property: channel
  target:
    name: camel-credentials
    creationPolicy: Owner
